---
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:burdzwastaken/concourse-spinnaker-resource.git
    branch: master
    private_key: ((ssh_key))
- name: docker-hub
  type: docker-image
  source:
    repository: burdz/concourse-spinnaker-resource
    email: ((docker_email))
    username: ((docker_username))
    password: ((docker_password))

jobs:
- name: build
  plan:
  - aggregate:
    - get: source-code
      trigger: true
    - get: alpine-edge
      trigger: true
      params:
        save: true
  - put: docker-hub
    params:
      build: source-code
      load_base: alpine-edge