---
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:pivotal-cf/spinnaker-resource.git
    branch: develop
    private_key: ((ssh_key))

- name: docker-hub
  type: docker-image
  source:
    repository: concourse/concourse-spinnaker-resource
    username: ((docker.username))
    password: ((docker.password))

- name: ubuntu-bionic
  type: docker-image
  source:
    repository: ubuntu
    tag: bionic

jobs:
- name: build
  plan:
  - aggregate:
    - get: source-code
      trigger: true
    - get: ubuntu-bionic
      trigger: true
      params:
        save: true
  - put: docker-hub
    params:
      build: source-code
      load_base: ubuntu-bionic