groups: []
resources:
- name: spinnaker
  type: spinnaker
  source:
    spinnaker_api: https://api.spincon.ci.cf-app.com:8085
    spinnaker_application: nvidia
    spinnaker_pipeline: bar
    spinnaker_x509_cert: ((spinnaker_x509_cert))
    spinnaker_x509_key: ((spinnaker_x509_key))
resource_types:
- name: spinnaker
  type: docker-image
  source:
    repository: concourse/spinnaker-resource-dev
jobs:
- name: trigger-pipeline
  plan:
  - put: spinnaker
    params:
      trigger_params:
        build_id: blah
        build_job_name: $BUILD_JOB_NAME
        atc_url: $ATC_EXTERNAL_URL

