---
resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:pivotal-cf/spinnaker-resource.git
    branch: develop
    private_key: ((private_key))

- name: docker-hub
  type: docker-image
  source:
    repository: concourse/spinnaker-resource-dev
    username: ((docker.username))
    password: ((docker.password))

- name: golang-alpine
  type: docker-image
  source:
    repository: golang
    tag: alpine

- name: ubuntu-bionic
  type: docker-image
  source:
    repository: ubuntu
    tag: bionic

jobs:
- name: build
  plan:
  - aggregate:
    - get: source-code
      trigger: true
    - get: ubuntu-bionic
      trigger: true
      params:
        save: true
    - get: golang-alpine
      trigger: true
      params:
        save: true
  - put: docker-hub
    params:
      build: source-code
      load_bases:
      - golang-alpine
      - ubuntu-bionic
