---
resource_types:
- name: spinnaker
  type: docker-image
  source:
    repository: burdz/concourse-spinnaker-resource

resources:
  - name: spinnaker
    type: spinnaker
    source:
      spinnaker_api: ((spinnaker-api))
      spinnaker_x509_cert: ((spinnaker-x509-cert))
      spinnaker_x509_key: ((spinnaker-x509-key))

jobs:
- name: trigger-pipeline
  plan:
  - put: spinnaker
    params:
      spinnaker_application: samplespinnakerapp
      spinnaker_pipeline: samplespinnakerapp
      trigger_params:
        build_id: (build ${BUILD_ID})
